config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages

end

app/models/user.rb
class User < ApplicationRecord

    validates_uniqueness_of :username

    def self.generate
        adjectives = ['blue', 'red', 'yellow', 'black', 'green']
        nouns = ['lion', 'fox', 'elephant', 'hippo', 'rat']
        number = rand.to_s[2..4]
        username = "#{adjectives.sample}_#{nouns.sample}_#{number}"
        User.create(username: username)

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  def current_user
    return @current_user if @current_user.present?

    if session[:user_id].present?
      @current_user = User.find( session[:user_id] )
    else
      @current_user = User.generate
      session[:user_id] = @current_user.id
      @current_user
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit

  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save

    # SendMessageJob.perform_later(@message, current_user)
    ActionCable.server.broadcast "room_channel_#{@message.room_id}", @message.content
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, class: 'form-inline') do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :room_id , value: room.id %>

  <div class="form-group row">
    <div class="col-10 p-0">
      <%= form.text_field :content, placeholder: "Type your message here ..", class: 'form-control' %>
    </div>

    <div class="col-2">
      <%= form.submit "Add Message", class:"btn btn-primary"%>
    </div>
  </div>

<% end %>

app/views/messages/_message.html.erb
<div class="message <%= 'me' if message.user.id == current_user.id %>">
  <div class="content_container">
    <div class="content">
      <h5> <%= message.content %> </h5>
    </div>
    <div class="auther">
      <p> <%= message.user.username %> </p>
    </div>
  </div>
</div>

app/views/messages/_mine.html.erb
<div class="message me">
  <div class="content_container">
    <div class="content">
      <h5><%= message.content %></h5>
    </div>
    <div class="auther">
      <p><%= message.user.username %></p>
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message">
  <div class="content_container">
    <div class="content">
      <h5><%= message.content %></h5>
    </div>
    <div class="auther">
      <p><%= message.user.username %></p>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , class: 'form-control'%>
  </div>

  <div>
    <%= form.submit 'Add Room' , class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<div id="user_id" hidden><%= current_user.id %></div>
<div id="room_id"><%= @room.try(:id) %></div>

<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <!--      <p>Hello Mr <%#= current_user.username %></p>-->
      <div class="card-body"><%= render 'form', room: Room.new %></div>
      <hr />

      <%@rooms.each do |room| %> <%= link_to room do %>
      <div class="card mb-2">
        <div class="card-body" onclick="reload(<%=room.id%>)"><%= room.name %></div>
      </div>
      <% end %> <% end %>
    </div>

    <div class="col-9">
      <% if @room.present? %>
      <div class="chat_room">
        <nav class="navbar navbar-light bg-light mb-4">
          <span class="navbar-brand mb-0 h1"><%= @room.name %></span>
          <ul class="navbar-nav">
            <li class="nav-item">Hello Mr <%= current_user.username %></li>
          </ul>
        </nav>
        <div id="messages">
          <% @room.messages.each do |message| %> <%= render 'messages/message' ,
          message:message %> <% end %>
        </div>
        <div class="chat_box">
          <%= render 'messages/form', message: Message.new , room:@room %>
        </div>
      </div>
      <%end %>
    </div>
  </div>
</div>

<script>
  function reload(room_id){
      location.replace("http://localhost:3000/rooms/"+room_id);
  }
</script>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>